import 'dart:io';
import 'package:path/path.dart' as path;
import '../config/config_model.dart';

class HookInstaller {
  static const _hooksDir = '.git/hooks';

  static void install(GitHooksConfig config) {
    final hooksDirectory = _getHooksDirectory();

    // Always clean all known hooks first, then reinstall from config
    for (final hookType in HookType.values) {
      _uninstallHook(hookType, hooksDirectory);
    }

    for (final entry in config.hooks.entries) {
      _installHook(entry.key, hooksDirectory);
    }
  }

  /// Removes all dart_husky managed hook files from .git/hooks/
  static void uninstall(GitHooksConfig config) {
    final hooksDirectory = _getHooksDirectory();

    for (final hookType in config.hooks.keys) {
      _uninstallHook(hookType, hooksDirectory);
    }
  }

  static void _installHook(HookType hookType, Directory hooksDirectory) {
    final hookFile = File(path.join(hooksDirectory.path, hookType.scriptName));
    hookFile.writeAsStringSync(_generateScript(hookType));

    // make the hook script executable
    Process.runSync('chmod', ['+x', hookFile.path]);

    print('✅ Installed ${hookType.scriptName}');
  }

  static void _uninstallHook(HookType hookType, Directory hooksDirectory) {
    final hookFile = File(path.join(hooksDirectory.path, hookType.scriptName));

    if (hookFile.existsSync()) {
      hookFile.deleteSync();
      print('🗑️  Removed ${hookType.scriptName}');
    } else {
      print('⚠️  ${hookType.scriptName} not found — skipping.');
    }
  }

  static Directory _getHooksDirectory() {
    final hooksPath = path.join(Directory.current.path, _hooksDir);
    final hooksDirectory = Directory(hooksPath);

    if (!hooksDirectory.existsSync()) {
      throw FileSystemException(
        'No .git/hooks directory found. Are you in a git repository?',
        hooksPath,
      );
    }

    return hooksDirectory;
  }

  static String _generateScript(HookType hookType) {
    final arg = hookType == HookType.commitMsg ? ' "\$1"' : '';
    return '''
#!/bin/sh
# Generated by dart_husky — do not edit manually

if command -v dart >/dev/null 2>&1; then
  dart run dart_husky run ${hookType.scriptName}$arg
elif command -v fvm >/dev/null 2>&1; then
  fvm dart run dart_husky run ${hookType.scriptName}$arg
else
  echo "❌ dart_husky: neither dart nor fvm found in PATH."
  echo "   Install Dart SDK or FVM and make sure it is in your PATH."
  exit 1
fi
''';
  }
}
